#include "fonts.h"

const struct LV_FONT lv_font[40] = 
{
    {"Sunny", "晴"},
    {"Clear", "晴"},
    {"Fair", "晴"},
    {"Fair", "晴"},
    {"Cloudy", "多云"},
    {"Partly Cloudy", "晴间多云"},
    {"Partly Cloudy", "晴间多云"},
    {"Mostly Cloudy", "大部多云"},
    {"Mostly Cloudy", "大部多云"},
    {"Overcast", "阴"},
    {"Shower", "阵雨"},
    {"Thundershower", "雷阵雨"},
    {"Thundershower with Hail", "雷阵雨冰雹"},
    {"Light Rain", "小雨"},
    {"Moderate Rain", "中雨"},
    {"Heavy Rain", "大雨"},
    {"Storm", "暴雨"},
    {"Heavy Storm", "大暴雨"},
    {"Severe Storm", "特大暴雨"},
    {"Ice Rain", "冻雨"},
    {"Sleet", "雨夹雪"},
    {"Snow Flurry", "阵雪"},
    {"Light Snow", "小雪"},
    {"Moderate Snow", "中雪"},
    {"Heavy Snow", "大雪"},
    {"Snowstorm", "暴雪"},
    {"Dust", "浮尘"},
    {"Sand", "扬沙"},
    {"Duststorm", "沙尘暴"},
    {"Sandstorm", "强沙尘暴"},
    {"Foggy", "雾"},
    {"Haze", "霾"},
    {"Windy", "风"},
    {"Blustery", "大风"},
    {"Hurricane", "飓风"},
    {"Tropical Storm", "热带风暴"},
    {"Tornado", "龙卷风"},
    {"Cold", "冷"},
    {"Hot", "热"},
    {"Unknown", "未知"},
};